//
// Created by vaish on 5/10/2021.
//

#ifndef AUTOTESTER_SPA_TEAM07_CODE07_SRC_SPA_SRC_PQL_QUERYPARSER_CLAUSELIST_H_
#define AUTOTESTER_SPA_TEAM07_CODE07_SRC_SPA_SRC_PQL_QUERYPARSER_CLAUSELIST_H_

#include "Clause.h"
#include <vector>

typedef std::vector<Clause *> ClauseList;

#endif //AUTOTESTER_SPA_TEAM07_CODE07_SRC_SPA_SRC_PQL_QUERYPARSER_CLAUSELIST_H_
